export const FETCH_TICKETS = 'FETCH_TICKETS';
export const FETCH_TICKETS_ERROR = 'FETCH_TICKETS_ERROR';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';

export const SET_FILTERS = 'SET_FILTERS';
