export const FETCH_TICKETS = 'FETCH_TICKETS';
export const FETCH_TICKETS_ERROR = 'FETCH_TICKETS_ERROR';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';

export const FETCH_EXCHANGE_RATES = 'FETCH_EXCHANGE_RATES';
export const FETCH_EXCHANGE_RATES_ERROR = 'FETCH_EXCHANGE_RATES_ERROR';
export const FETCH_EXCHANGE_RATES_SUCCESS = 'FETCH_EXCHANGE_RATES_SUCCESS';

export const SET_FILTERS = 'SET_FILTERS';
